# Generated by Django 6.1.1 on 2026-09-29 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('order_id', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('reason', models.CharField(blank=True, max_length=30)),
                ('decision', models.CharField(max_length=20)),
                ('rule', models.CharField(blank=True, max_length=40)),
                ('reasons', models.JSONField(default=list)),
                ('injection_flag', models.BooleanField(default=False)),
                ('ai_notes', models.TextField(blank=True)),
                ('reply', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField()),
                ('final_sale', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('refunded_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='refunds.customer')),
            ],
        ),
    ]
