# Generated by Django 6.1.1 on 2026-09-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='ai_status',
            field=models.CharField(default='not_used', max_length=24),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
